name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    needs: train
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/myimage:latest

    - name: Run Docker container
      run: docker run ${{ secrets.DOCKER_USERNAME }}/myimage:latest

    - name: Evaluate score
      run: |
        # Add code to evaluate the score returned by test.py
        # Example:
        score=$(docker run ${{ secrets.DOCKER_USERNAME }}/myimage:latest python test.py)
        if [ $(echo "$score > 0.60" | bc) -eq 1 ]; then
          echo "Test succeeded"
          exit 0
        else
          echo "Test failed"
          exit 1
        fi
      shell: bash
      continue-on-error: true
