name: Train

on:
  pull_request:
    branches:
      - main

env:
  USERNAME: dimley
  PASSWORD: Hope@@2024

jobs:
  build:
    name: train and push image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build . -t ${{ env.USERNAME }}/myimage:latest
        docker push ${{ env.USERNAME }}/myimage:latest

  test:
    name: fetch image and test
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull ${{ env.USERNAME }}/myimage:latest

    - name: Run Docker container
      run: docker run ${{ env.USERNAME }}/myimage:latest

    - name: Evaluate score
      run: |
        # Add code to evaluate the score returned by test.py
        # Example:
        score=$(docker run ${{ env.USERNAME }}/myimage:latest)
        if [ $(echo "$score > 0.60" | bc) -eq 1 ]; then
          echo "Test succeeded"
          exit 0
        else
          echo "Test failed"
          exit 1
        fi
      shell: bash
      continue-on-error: false
