name: Train

on:
  pull_request:
    branches:
      - main

env:
  USERNAME: ${{ secrets.DOCKER_USERNAME }}
  PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build . -t ${{ env.USERNAME }}/myimage:latest
        docker push ${{ env.USERNAME }}/myimage:latest
